### ISSUE TITLE
Error after upgrading to version 2.1.0

### ISSUE THREAD

**Issue by jvandijk** [FokkeZB/ti-64#10]
After upgrading from version 0.1.0 to version 2.1.0 using `npm update -g ti-64`, I reran the command to check which modules are correct. Now I run into the following error:

```
/usr/local/lib/node_modules/ti-64/index.js:153
          async.mapSeries(modules, function forEach(module, next) {
                          ^
ReferenceError: modules is not defined
    at handle (/usr/local/lib/node_modules/ti-64/index.js:153:27)
    at /usr/local/lib/node_modules/ti-64/node_modules/timodules/lib/timodules.js:48:7
    at /usr/local/lib/node_modules/ti-64/node_modules/timodules/lib/timodules.js:29:7
    at /usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/tiapp/lib/tiapp.js:19:15
    at Parser.<anonymous> (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/ti-64/node_modules/timodules/node_modules/xml2js/node_modules/sax/lib/sax.js:1293:29)
```

Are you aware of this?

**Comment by jvandijk** [comment]
Nice work! I can confirm this works.
